### ISSUE TITLE
[Q] Question from SNG author.

### ISSUE THREAD

**Issue by swamidass** [UCLCheminformatics/ScaffoldGraph#1]
## ❓ Questions & Help

Glad to see our work taken up in a better library. Are you taking contributions tot his project?

**Comment by OliverBScott** [comment]
Hi, thank you! I would be very happy to receive any contributions to the project. I have written a small contribution [guideline](https://github.com/UCLCheminformatics/ScaffoldGraph/blob/master/CONTRIBUTING.md). I would love to hear any ideas or suggestions.
