### ISSUE TITLE
about the visualization utils

### ISSUE THREAD

**Issue by 707-Moira** [UCLCheminformatics/ScaffoldGraph#13]
## ❓ Questions & Help
Hello~
When I have installed the ipycytoscape module today and updated scaffoldgraph, it seems I still have problem in importing cytoscape from the vis uilt. The error proved to be ' no module named scaffoldgraph.vis.'. I have checked packages in my envs and found there seems truly no vis module. Is there anything wrong with my implementation? 
(Maybe I'll choose to use ipycytoscape directly.

**Comment by OliverBScott** [comment]
Hi, I am not sure if you found the answer. The visualization utilities will be available in the next release. If you want to use them now you can install from the master branch.

**Comment by 707-Moira** [comment]
> Hi, I am not sure if you found the answer. The visualization utilities will be available in the next release. If you want to use them now you can install from the master branch.

I may have solved the problem by copying the source code directly to my envs. I’m wondering if there is a function to output what I have arranged in the interactive window as picture format, as I currently haven’t found how to realize it  in the source code. I presume this may be achieved directly through ipycytoscape, but there seems no such information in that repository (or maybe I missed sth). I have to consider using networkx to finish the drawing now...

**Comment by OliverBScott** [comment]
There isn't a function for exporting the window as an image within scaffoldgraph. I am not even sure there is one in ipycytoscape unfortunately, although I think this would be a great feature! I found [this](https://github.com/QuantStack/ipycytoscape/issues/75) issue related to saving/exporting images although it seems like not much progress has been made, it may be worth making a comment on that thread.  For now, I have been using screenshots of the window although I realise this is not ideal.

Concerning networkx, I always found the drawing code particularly clunky, although if you end up using it and create something decent, I would love to integrate a networkx (or any other tool) based visualisation tool into the scaffoldgraph source code. 

I have also found [this](https://github.com/plotly/dash-cytoscape) tool based on cytoscapejs/plotly. Looks like it supports image export too. Let me know if you find a good soloution.

**Comment by 707-Moira** [comment]
> There isn't a function for exporting the window as an image within scaffoldgraph. I am not even sure there is one in ipycytoscape unfortunately, although I think this would be a great feature! I found [this](https://github.com/QuantStack/ipycytoscape/issues/75) issue related to saving/exporting images although it seems like not much progress has been made, it may be worth making a comment on that thread. For now, I have been using screenshots of the window although I realise this is not ideal.
> 
> Concerning networkx, I always found the drawing code particularly clunky, although if you end up using it and create something decent, I would love to integrate a networkx (or any other tool) based visualisation tool into the scaffoldgraph source code.
> 
> I have also found [this](https://github.com/plotly/dash-cytoscape) tool based on cytoscapejs/plotly. Looks like it supports image export too. Let me know if you find a good solution.

Many thanks to the tool 'dash' and I found it quite useful (even for other kind of figures). And I'm trying to integrate the drawing function of rdkit in it. More important function of visualization to me is the change of color with each node, as we always need to give value to each node and see all that distribution. Maybe the change of the color of each node will be a good choice, though the background of the drawing of the mol seems need to be set as trasparent, which I haven't found a way to realize. Just the same as the figure shown in the orignal paper of scaffold tree which is shown below (the author may not generate the figure automatically but I'd like to have a try as my data may be a little huge). Anyway, this provides an alternative worth trying.   
![image](https://user-images.githubusercontent.com/60834645/103722747-99cad000-500b-11eb-8087-c13891040ee5.png)

**Comment by OliverBScott** [comment]
> > There isn't a function for exporting the window as an image within scaffoldgraph. I am not even sure there is one in ipycytoscape unfortunately, although I think this would be a great feature! I found [this](https://github.com/QuantStack/ipycytoscape/issues/75) issue related to saving/exporting images although it seems like not much progress has been made, it may be worth making a comment on that thread. For now, I have been using screenshots of the window although I realise this is not ideal.
> > Concerning networkx, I always found the drawing code particularly clunky, although if you end up using it and create something decent, I would love to integrate a networkx (or any other tool) based visualisation tool into the scaffoldgraph source code.
> > I have also found [this](https://github.com/plotly/dash-cytoscape) tool based on cytoscapejs/plotly. Looks like it supports image export too. Let me know if you find a good solution.
> 
> Many thanks to the tool 'dash' and I found it quite useful (even for other kind of figures). And I'm trying to integrate the drawing function of rdkit in it. More important function of visualization to me is the change of color with each node, as we always need to give value to each node and see all that distribution. Maybe the change of the color of each node will be a good choice, though the background of the drawing of the mol seems need to be set as trasparent, which I haven't found a way to realize. Just the same as the figure shown in the orignal paper of scaffold tree which is shown below (the author may not generate the figure automatically but I'd like to have a try as my data may be a little huge). Anyway, this provides an alternative worth trying.
> ![image](https://user-images.githubusercontent.com/60834645/103722747-99cad000-500b-11eb-8087-c13891040ee5.png)

I am going to have a go at playing around with a dash based visualization utility, although I don't know when I will have enough time to create something viable. The dash-cytoscape implementation shouldn't be too different from the ipycytoscape  implementation as they both use cytoscapejs. The style-sheet used here should be transferable. Concerning  colouring the background of a node this is a little trickier (to get a nice color map, yet entirely possible!), rather it would be much easier to colour the node border by adding a 'color' attribute to each node and updating the stylesheet accordingly. I drafted  a quick idea colouring the border/background based on the scaffolds hierarchy. Of course, this could be extended to any scaffold/molecule attribute:

```python
import scaffoldgraph as sg
import matplotlib.pyplot as plt
import matplotlib as mpl

from scaffoldgraph.vis.notebook import cytoscape


def f2hex(f2rgb, f):
    rgb = f2rgb.to_rgba(f)[:3]
    return '#%02x%02x%02x' % tuple([int(255 * fc) for fc in rgb])


# Create graph.
tree = sg.ScaffoldTree.from_sdf('my_mols.sdf')

# Create color map based on 'hierarchy' attribute.
vmin, vmax = 1, 6
cmap = plt.get_cmap('inferno_r')
cnorm = mpl.colors.Normalize(vmin, vmax)
scalarmap = mpl.cm.ScalarMappable(norm=cnorm, cmap=cmap)

# Map colors to nodes based on 'hierarchy attribute'.
for node, data in tree.get_scaffold_nodes(True):
    c = f2hex(scalarmap, data['hierarchy'])
    data['color'] = c
  
# Create style for nodes with a 'color' attribute.
border_style = {
    "selector": "node[color]",
    "style": {
        "border-color": "data(color)",
        "border-width": "6",
    }
}

# Create visualizer.
vis = cytoscape.CytoscapeVisualizer(tree)
vis.style.append(border_style)  # Add border style.

# Render for a scaffold.
vis.draw_for_scaffold('c1ccccc1')
```

And to colour the backgrounds (I created a custom colour map based on the figure you showed from the paper):

```python
from scaffoldgraph.vis import embed_node_mol_images
from rdkit.Chem.Draw import rdMolDraw2D

# Make backgrounds transparent.
drawOpts = rdMolDraw2D.MolDrawOptions()
drawOpts.clearBackground = False

# Embed images into nodes.
embed_node_mol_images(tree, draw_options=drawOpts, skip_existing=False)

# Custom cmap (no colours that are too dark).
cmap = mpl.colors.LinearSegmentedColormap.from_list('white2yellow', ['#FFFFFF', '#F2EC54'])
cnorm = mpl.colors.Normalize(vmin, vmax)
scalarmap = mpl.cm.ScalarMappable(norm=cnorm, cmap=cmap)

# Map colors to nodes.
for node, data in tree.nodes(data=True):
    if data['type'] == 'molecule':  # Neutral color for molecules.
        data['color'] = '#EEEEEE'
    elif data['type'] == 'scaffold':  # scaffold color based on hierarchy.
        c = f2hex(scalarmap, data['hierarchy'])
        data['color'] = c

# Create background style.
background_style = {
    "selector": "node[color]",
    "style": {
        "background-color": "data(color)",
    }
}

# Create visualizer.
vis = cytoscape.CytoscapeVisualizer(tree)
vis.style.append(background_style)  # Add border style.

# Render for scaffold.
vis.draw_for_scaffold('c1ccccc1')
```

![Screen Shot 2021-01-06 at 11 27 37](https://user-images.githubusercontent.com/33868948/103763788-414b0100-5012-11eb-9948-19727233e7fa.png)

I am not sure whether the mol images should have a transparent background by default or whether I should add it as an option to the visualizer. I will also probably add some functions to create colour maps based on node attributes and adding these as attributes to the graph to make this process easier.

**Comment by 707-Moira** [comment]
Another problem may lie on the compatibility on different python versions. I ran quite well on python 3.7. However, considering version 3.5 and 3.6, there seem some bugs, especially that python 3.5 cannot support f-string, which relates to some outputs. If this currently must be run on python 3.7 (as rdkit may not support well beyond 3.7), maybe you can consider illustrate it in README

**Comment by OliverBScott** [comment]
> Another problem may lie on the compatibility on different python versions. I ran quite well on python 3.7. However, considering version 3.5 and 3.6, there seem some bugs, especially that python 3.5 cannot support f-string, which relates to some outputs. If this currently must be run on python 3.7 (as rdkit may not support well beyond 3.7), maybe you can consider illustrate it in README

I agree with respect to python 3.5, I will make a note of this in the README. What issues have you witnessed with python 3.6? All of the tests are successful using python 3.6 (travis-ci), although the vis modules currently have no tests.As for rdkit the [conda-forge channel](https://anaconda.org/conda-forge/rdkit/files) seems to have builds for  3.6, 7, 8 and 9. The rdkit channel seems to only have builds for 3.6 and 3.7 although is also a version behind.
