### ISSUE TITLE
[Q]Can not read SMILES file

### ISSUE THREAD

**Issue by quanquan0537** [UCLCheminformatics/ScaffoldGraph#2]
this command "scaffoldgraph network biomol.smi biomol.tmp " give an error as shown below.

scaffold-graph: 15:21:29 19315 INFO: Generating Scaffold Network...
scaffold-graph: 15:21:29 19315 CRITICAL: Unknown error: Python argument types in
    SmilesMolSupplier.__init__(SmilesMolSupplier, str, int, int, int, bool, bool)
did not match C++ signature:
    __init__(_object*)
    __init__(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > data, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > delimiter=' ', int smilesColumn=0, int nameColumn=1, bool titleLine=True, bool sanitize=True)
scaffold-graph: 15:21:29 19315 INFO: Exiting scaffoldgraph...

But we can read "biomol.smi" using "Chem.SmilesMolSupplier".How to solve this problem?

**Comment by OliverBScott** [comment]
Hi, sorry about this! This should now be fixed in master 4f4f2ef47fdd88ac878bc56ba27d4971c6f8bedb
