### ISSUE TITLE
A question about visualizing scaffold networks[Q]

### ISSUE THREAD

**Issue by yrq3027** [UCLCheminformatics/ScaffoldGraph#22]
## ❓ Questions & Help

When I using jupyter lab run relation codes to create and visualize a scaffold network, it could not draw the picture like follows:
![Snipaste_2021-11-16_15-32-28](https://user-images.githubusercontent.com/46614261/141940715-1da2497f-d0e4-4f52-b2f7-fd9d6ee67049.jpg)
Could give me some advices to solve this problem? Thank you!

**Comment by OliverBScott** [comment]
Hi, this seems to be a problem with your ipycytoscape installation. When using ipycytoscape with Jupyter lab you may need to follow a couple of extra steps. I would advise you to follow the instructions in their documentation:

- https://ipycytoscape.readthedocs.io/en/latest/installing.html
- https://github.com/cytoscape/ipycytoscape#for-jupyterlab-1x-or-2x 

I will make sure to make a note of these additional steps for Jupyter lab users in the project's readme. Thanks for pointing this out and let me know if you have further issues.

**Comment by yrq3027** [comment]
Thank you! I solved this problem on Windows. Some problem in Ubuntu I think it will be solved as soon!

**Comment by yrq3027** [comment]
Codes running successful both on windows and ubuntu after I update jupyter lab to 3.0.
