### ISSUE TITLE
[Q] Aromatic bonds removal

### ISSUE THREAD

**Issue by Aleksashka11** [UCLCheminformatics/ScaffoldGraph#23]
## ❓ Questions & Help

Hi!
Thank you for this really useful and great module! But there is a problem.
When generating scaffold tree, aromatic bonds are removed. Therefore, it is rather complicated to work with the structures returned. Is there a way how to solve this problem?

**Comment by OliverBScott** [comment]
Hi, thanks for getting in touch!

There could be many factors behind this issue. I don't have a huge amount of time to debug/update this package anymore, so it would be really helpful if you could provide a couple examples to help me get started.

**Comment by Aleksashka11** [comment]
In your source code we found a comment that clearly indicates that aromatic bonds are converted to double bonds in order to avoid the creation of chemically not meaningful rings. However, in a number of tasks it is engaging to work not with a real molecule but with a chemical query (as it happens in SMARTS and modified mols for chemical queries).

Therefore, we are interested in whether it is possible to provide a scheme where aromatic bonds are not removed? If such an option is not ok for you, we can make a pull request with all necessary modifications. To do this, please, provide us with the piece of code where the aromatic bond is substituted by the double bond.

For instance, in our sample we are getting a fragment (fig. 1) presented below that should be matched with the structure on figure 2 but that doesn’t happen.
![2022-12-13_13-59-33](https://user-images.githubusercontent.com/59337516/207312322-65e61f35-27f7-4f6b-aa1f-bf338d5a2b3e.png)
![2022-12-13_13-59-49](https://user-images.githubusercontent.com/59337516/207312349-3dfd2d46-d42f-45d2-95e8-ca54e72beee1.png)

**Comment by OliverBScott** [comment]
Discussed offline.
